### ISSUE TITLE
Error when trying to delete user from a group

### ISSUE THREAD

**Issue by dregad** [mantisbt-plugins/Usergroups#2]
Clicking *Delete* link in manage_user_edit_page.php yields

APPLICATION ERROR 2500
Plugin "sergroups" is not registered.

Typo here:
https://github.com/mantisbt-plugins/Usergroups/blob/ef8d78a64a5ffa0bb5c6e5bd04097ed2aeaa151a/Usergroups_api.php#L36

**Comment by ghost** [comment]
This is fixed inversion 2.12
