### ISSUE TITLE
Security: use parameterized DB queries

### ISSUE THREAD

**Issue by dregad** [mantisbt-plugins/Usergroups#3]
You really need to stop using inline variables as parameters in your SQL statements, particularly with unescaped data from untrusted, user input. This exposes you to SQL injection attacks.

For example (from manage_usergroup_add.php, but same problem throughout the plugin):

### BAD
```php
	$query = "INSERT INTO {plugin_Usergroups_usergroup} ( group_id,user_id ) VALUES ('$groupid', '$userid')";
	$res=db_query($query);
```

### GOOD
With legacy database API calls:
```php
	$param = [(int)$groupid, (int)$userid];
	$query = "INSERT INTO {plugin_Usergroups_usergroup} ( group_id,user_id ) VALUES ( " . db_param() . ", " . db_param() . ")";
	$res=db_query($query);
```

or with DbQuery object
```php
	$param = [(int)$groupid, (int)$userid];
	$query = new DbQuery( "INSERT INTO {plugin_Usergroups_usergroup} ( " . implode( ', ', array_keys( $param ) ) . " ) VALUES :param")";
	$query->bind( 'param', $param );
	$query->execute(); 
```

**Comment by ghost** [comment]
Hi Damian,
You are right, this is still old code. Normally I try to adjust when another update is due😁.
Now I am cruising in Hungary & Romania, will pick it up upon my return.
Kind regards,
Cas

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Damien Regad ***@***.***>
Sent: Tuesday, August 20, 2024 10:55:38 AM
To: mantisbt-plugins/Usergroups ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mantisbt-plugins/Usergroups] Security: use parameterized DB queries (Issue #3)


You really need to stop using inline variables as parameters in your SQL statements, particularly with unescaped data from untrusted, user input. This exposes you to SQL injection attacks.

For example (from manage_usergroup_add.php, but same problem throughout the plugin):

BAD

        $query = "INSERT INTO {plugin_Usergroups_usergroup} ( group_id,user_id ) VALUES ('$groupid', '$userid')";
        $res=db_query($query);

GOOD

With legacy database API calls:

        $param = [(int)$groupid, (int)$userid];
        $query = "INSERT INTO {plugin_Usergroups_usergroup} ( group_id,user_id ) VALUES ( " . db_param() . ", " . db_param() . ")";
        $res=db_query($query);

or with DbQuery object

        $param = [(int)$groupid, (int)$userid];
        $query = new DbQuery( "INSERT INTO {plugin_Usergroups_usergroup} ( " . implode( ', ', array_keys( $param ) ) . " ) VALUES :param")";
        $query->bind( 'param', $param );
        $query->execute();

**Comment by ghost** [comment]
Think I handled all unsecure db updates in version 2.12
